### ISSUE TITLE
Datenbankfehler macht Plugin nicht nutzbar.

### ISSUE THREAD

**Issue by Nico4898** [mreichardt1992/wp-bsd-verwaltung#19]
Error-Log:

mod_fcgid: stderr: WordPress-Datenbank-Fehler Can't create table 'ffw-sql.cHkCt47_bsd_bookings' (errno: 150) f\xc3\xbcr Abfrage CREATE TABLE IF NOT EXISTS cHkCt47_bsd_bookings (, referer: .../wp-admin/plugin-install.php?s=bsd+verwaltung&tab=search&type=term |   |   |   | Apache-Fehler

**Comment by mreichardt1992** [comment]
Vielen Dank für die Meldung. Kontaktiere mich bitte unter m@xreichardt.de, dann gehen wir der Sache auf den Grund.

**Comment by mreichardt1992** [comment]
Fehler in Server-Konfiguration, kein Fehler im Plugin.
